### ISSUE TITLE
new problem 

### ISSUE THREAD

**Issue by bibi-blocksberg** [WardPearce/Discord-Server-List#4]
Traceback (most recent call last):
  File "run.py", line 36, in query_loop
    async with aiohttp_session.get("https://districtnine.host/api/serverquery/?ip={}".format(values["server-ips"])) as r:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host districtnine.host:443 ssl:None [No address associated with hostname]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fae7faeaba8>

**Comment by LubricantJam** [comment]
@WardPearce

**Comment by WardPearce** [comment]
https://github.com/DistrictNineHost/Discord-Server-List#development-status

**Comment by WardPearce** [comment]
New rewrite should of fixed these issues :)
